project:
    path:     /
    defaults: { _controller: "BMGBookToolBundle:Project:index" }

project_show:
    path:     /{id}/show
    defaults: { _controller: "BMGBookToolBundle:Project:show" }

project_new:
    path:     /new
    defaults: { _controller: "BMGBookToolBundle:Project:new" }

project_create:
    path:     /create
    defaults: { _controller: "BMGBookToolBundle:Project:create" }
    requirements: { _method: post }

project_edit:
    path:     /{id}/edit
    defaults: { _controller: "BMGBookToolBundle:Project:edit" }

project_update:
    path:     /{id}/update
    defaults: { _controller: "BMGBookToolBundle:Project:update" }
    requirements: { _method: post|put }
