socialnetwork:
    path:     /
    defaults: { _controller: "BMGBookToolBundle:SocialNetwork:index" }

socialnetwork_show:
    path:     /{id}/show
    defaults: { _controller: "BMGBookToolBundle:SocialNetwork:show" }

socialnetwork_new:
    path:     /new
    defaults: { _controller: "BMGBookToolBundle:SocialNetwork:new" }

socialnetwork_create:
    path:     /create
    defaults: { _controller: "BMGBookToolBundle:SocialNetwork:create" }
    requirements: { _method: post }

socialnetwork_edit:
    path:     /{id}/edit
    defaults: { _controller: "BMGBookToolBundle:SocialNetwork:edit" }

socialnetwork_update:
    path:     /{id}/update
    defaults: { _controller: "BMGBookToolBundle:SocialNetwork:update" }
    requirements: { _method: post|put }

