userrentallink:
    path:     /
    defaults: { _controller: "BMGBookToolBundle:UserRentalLink:index" }

userrentallink_show:
    path:     /{id}/show
    defaults: { _controller: "BMGBookToolBundle:UserRentalLink:show" }

userrentallink_new:
    path:     /new
    defaults: { _controller: "BMGBookToolBundle:UserRentalLink:new" }

userrentallink_create:
    path:     /create
    defaults: { _controller: "BMGBookToolBundle:UserRentalLink:create" }
    requirements: { _method: post }

userrentallink_edit:
    path:     /{id}/edit
    defaults: { _controller: "BMGBookToolBundle:UserRentalLink:edit" }

userrentallink_update:
    path:     /{id}/update
    defaults: { _controller: "BMGBookToolBundle:UserRentalLink:update" }
    requirements: { _method: post|put }

userrentallink_delete:
    path:     /{id}/delete
    defaults: { _controller: "BMGBookToolBundle:UserRentalLink:delete" }
    requirements: { _method: post|delete }