userrecoverypasswordhash:
    path:     /
    defaults: { _controller: "BMGBookToolBundle:UserRecoveryPasswordHash:index" }

userrecoverypasswordhash_show:
    path:     /{id}/show
    defaults: { _controller: "BMGBookToolBundle:UserRecoveryPasswordHash:show" }

userrecoverypasswordhash_new:
    path:     /new
    defaults: { _controller: "BMGBookToolBundle:UserRecoveryPasswordHash:new" }

userrecoverypasswordhash_create:
    path:     /create
    defaults: { _controller: "BMGBookToolBundle:UserRecoveryPasswordHash:create" }
    requirements: { _method: post }

userrecoverypasswordhash_edit:
    path:     /{id}/edit
    defaults: { _controller: "BMGBookToolBundle:UserRecoveryPasswordHash:edit" }

userrecoverypasswordhash_update:
    path:     /{id}/update
    defaults: { _controller: "BMGBookToolBundle:UserRecoveryPasswordHash:update" }
    requirements: { _method: post|put }
